### ISSUE TITLE
VoiceMessages submission issue. 

### ISSUE THREAD

**Issue by itmesarah** [riolubruh/VoiceMessages#3]
On line 372 you've got `module.exports = class YABDP4Nitro`, which references another plugin we will not support.

**Comment by riolubruh** [comment]
Oh wow, yep. That's a copy-paste error from when I was reusing some of basic structure from my other plugin. Shit happens.

**Comment by riolubruh** [comment]
Fixed.

**Comment by AceLikesGhosts** [comment]
Any updates on getting this into the BD plugin repo? (:

**Comment by AceLikesGhosts** [comment]
go bother arven thank you love u
